[id=first-prog]
== Первая программа

При изучении языка программирования можно пойти двумя путями.

Первый путь, пожалуй, более правилен с академической точки зрения. Сначала мы заучиваем ключевые слова языка и основные концепции, затем учимся строить из них синтаксически корректные конструкции, и в конце долгого пути наконец получаем завершенную программу, готовую к выполнению. Но этот путь вряд ли будет быстрым и увлекательным. Дело в том, что мы сможем увидеть хоть какой-то результат лишь в самом конце изучения языка, а до этого момента придется обходиться без обратной связи.

Есть и второй путь. Он не столь совершенен с теоретической точки зрения, но гораздо увлекательнее первого. Мы начнем с самой простой из возможных программ, которая делает самое элементарное действие, которое мы можем обнаружить: печатает приветствие на экране. Несмотря на простоту, это будет полностью завершенная программа, которая содержит все те же элементы, что и гораздо более сложные программы. Возможно, не все из них будут очевидны с самого начала (хотя мы постараемся сделать их интуитивно понятными).

Составив программу, мы разберемся, какие действия нужно сделать, чтобы заставить компьютер выполнить ее. Когда все заработает, у нас будет рабочий каркас, который можно использовать для проверки действия только что изученных элементов языка. Мы просто будем добавлять их в работающую программу и смотреть полученный результат. Это даст нам возможность постепенно изучать язык и при этом получать быструю обратную связь. Этот подход хорошо зарекомендовал себя на практике в течение десятилетий, и мы им воспользуемся.

Приступим. Что делает воспитанный человек, входя в общество? Разумеется, здоровается. Давайте и мы поприветствуем мир языка C, в который мы вступаем.

=== Программа «Hello World!»

Пожалуй, это одна из самых простых программ, которая делает что-то осмысленное, а именно: выводит приветствие на консоль. Вот ее полный текст:

[source,c]
----
/* <1>
Это многострочный комментарий.
Обычно подобный комментарий приводится в начале программы.
Он может описывать ее назначение, примененные алгоритмы,
имя автора, его контактные данные, лицензию и что угодно еще,
что может оказаться полезным читателю кода.

Компилятор полностью игнорирует комментарии.
*/

#include <stdio.h> <2>
#define GREETING "Hello World!\n" <3>

int main(void) <4>
{ <5>
	// Вывод приветствия на экран консоли <6>
    printf(GREETING); <7><8>
    return 0; <9>
} <10>
----
<1> -- многострочный комментарий.
<2> -- включение заголовочного файла.
<3> -- определение текстового литерала через макрос.
<4> -- главная функция программы.
<5> -- скобка, открывающая функцию.
<6> -- однострочный комментарий.
<7> -- вывод приветствия на консоль.
<8> -- разделитель.
<9> -- возврат в операционную систему.
<10> -- скобка, закрывающая функцию.

Рассмотрим каждый из этих элементов немного подробнее, отложив детальное изучение до следующих глав.

=== Комментарии

В основном комментарии имеют смысл только для читающего текст программы человека. Копилятор игнорирует их содержимое. На самом деле, как мы увидим вскоре, они просто удаляются на одной из фаз компиляции.

В языке C используются два вида комментариев: онострочный и многострочный.

==== Многострочный комментарий

[source,c]
----
/*
Это многострочный комментарий.
Обычно подобный комментарий приводится в начале программы.
Он может описывать ее назначение, примененные алгоритмы,
имя автора, его контактные данные, лицензию и что угодно еще,
что может оказаться полезным читателю кода.

Компилятор полностью игнорирует комментарии.
*/
----

Многострочный комментарий начинается последовательностью литер `/\*` и заканчивается последовательностью `*/`.

==== Однострочный комментарий

[source,c]
----
	// Вывод приветствия на экран консоли
----

Однострочный комментарий компактнее, но при этом его возможности более ограниченны. Он начинается последовательностью литер `//` и продолжается до конца строки.

=== Включение заголовочного файла.

[source,c]
----
#include <stdio.h>
----

Язык C чрезвычайно минималистичен. Подобно Микеланджело, его создатели также отсекали от глыбы мрамора все лишнее, оставив лишь самое необходимое.

Те, для кого C -- не первый язык программирования, порой бывают удивлены, что в составе языка нет даже средства вывода сообщения на консоль. Хотя по сути удивляться годесь нечему: во встраиваемой системе может попросту не оказаться дисплея, пригодной для вывода строки текста, и его заменяют несколько светодиодных индикаторов. В таком случае не имеет смысла занимать скромные ресурсы микроконтроллера кодом поддержки работы с консолью, который может никогда не потребоваться.

Разработчики C пошли по другому пути. Они оставили минимальное ядро языка, к которому при необходимости подключаются библиотечные модули. Это позволяет не только избегать напрасной растраты ресурсов, но и выполнять тонкую настройку среды под конкретную реализацию аппаратуры.

Впрочем, при этом возникает одна проблема. Для того, чтобы вызвать библиотечную функцию, компилятор должен знать о ней необходимую информацию. Другими словами, нужно предварительно __объявить__ функцию. К счастью, нет необходимости делать это вручную. Вместе с библиотеками в состав среды разработки входит набор файлов с готовыми объявлениями, так называемые __заголовки__ (headers). Чтобы использовать функции из некоторой библиотеки, достаточно подключить к программе соответствующий файл заголовка. Именно это делает директива `#include <__file__.h>`.

В нашем случае к программе подключается заголовок `<stdio.h>` (standard input/output), в котором описаны средства стандартной библиотеки ввода/вывода. Это необходимо для того, чтобы впоследствии вызвать функцию `printf`.

В принципе файл заголовка можно подключить в любом месте до использования объявленной в нем функции, но по традиции все заголовки подключаются в начале программы. Мы сделает так же.

=== Определение текстовой строки через макрос

[source,c]
----
#define GREETING "Hello World!\n"
----

Эта конструкция связывает текст приветствия, выводимого на экран, с символическим именем `GREETING` (я пока намеренно не использую слово __идентификатор__, с которым мы познакомимся позже).

Текстовая строка заключается в двойные кавычки. Помимо литер, которые будут выведены на экран, в конце есть также последовательность `\n`, которая, как мы увидим вскоре, на экране отсутствует. Это так называемая __escape-последовательность__, которая заставляет консоль перейти на новую строку. На данный момент нам достаточно этих сведений.

Конструкция `#define` является __макроопределением__ (или коротко __макросом__). В данном случае она связывает имя `GREETING` со значением "Hello World!\n", а именно: каждый раз, когда компилятор встречает в тексте программы слово `GREETING`, он подставляет вместо него "Hello World!\n". Сейчас не будем вдаваться в детали, __зачем__мы это делаем; язык вполне позволяет обойтись без этого и использовать непосредственно значения в нужных местах программы. Вернемся к этому вопросу позже в разделе, посвященном макросам и их использованию.


=== Главная функция программы

[source,c]
----
int main(void)
----

Язык C следует так называемой __парадигме структурного программирования__footnote:[https://tinyurl.com/dcjhd75m]. Ее суть заключается в том, что программа представляется в виде иерархической структуры __блоков__footnote:[https://tinyurl.com/2rv5xzc3]. Одним из видов строительных блоков в парадигме структурного программирования является __подпрограмма__footnote:[https://tinyurl.com/4d8463b3ъ]; в языке C их называют __функциями__.

Про функции мы поговорим отдельно в соответствующем разделе. Сейчас же нам достаточно знать, что среди функций есть особенная с именем `main`. Именно с нее по умолчанию начинается выполнение программы.

Допустимо несколько вариантов объявления функции `main`. Для нашей цели вполне подходит простейший, в котором функция не принимает __параметров__ (об этом говорит слово `void` в круглых скобках сразу после имени функции) и по завершении работы возвращает целочисленный результат (на это указывает слово `int` перед именем функции).

.Куда передается результат работы программы?
****
Когда разработанная нами программа запускается под управлением ОС, у нее есть возможность вернуть ОС одно целочисленное значение (__код завершения__). Мы сами определяем семантику этого значения. Однако общепринято возвращать значение `0`, если программа отработала и завершилась нормально, и ненулевой код ошибки, если что-то пошло не так. Коды ошибки определяет сам автор программы, и правила хорошего тона диктуют, что он должен описать их в документации к своей программе.

Если же программа выполняется на "голом железе" (bare-metal), она никогда не заканчивается, и использовать механизм кода завершения не имеет смысла.
****

=== Открывающая и закрывающая функцию скобки

Сразу же после объявления функции `main` находится открывающая фигурная скобка `{`. С этой точки начинается код функции и продолжается до парной ей закрывающей скобки `}`.

Именно фигурные скобки определяют структуру программы на C. Во времена Кернигана и Ритчи в качестве консоли обычно использовалась пишущая машинка, поэтому для экономии бумаги открывающую скобку размещали в той же строке,что и объявление функции. На видеомониторе экономить бумагу нет необходимости, поэтому встречается другой вариант: открывающая скобка располагается на отдельной строке, над парной к ней закрывающей. какой вариант использовать - исключительно дело вкуса, поскольку это оказывает влияние только на читаемость кода. Компилятор C (в отличие, например, от интерпретатора Python) не обращает никакого внимания на форматирование исходного текста, поэтому вы можете выбрать тот вариант, который вам нравится, или даже тзобрести свой собственный.

=== Вывод приветствия на консоль

[source,c]
----
    printf(GREETING);
----

Одним из способов вывода сообщения на консоль является вызов библиотечной функции `printf`. В отличие от `main` мы не пишем ее исходный код, поскольку он уже присутствует в одной из стандартных библиотек, поставляемых вместе с компиляторомfootnote:[Функция `printf` не всегда доступна, поскольку в минимальной конфигурации в системе может просто не быть консоли.].

Эта функция обладает очень большими возможностями, и ее полное описание займет большую главу. В простейшем случае (нашем) функция имеет единственный строковый арогумент и просто выводит его на консоль (не забываем про escape-последовательности!).

После завершения работы этой функции на консоли в текущей позиции появится сообщение:

[console]
Hello World!

После этого произойдет переход на новую строку.

=== Разделитель

Обратите внимание на разделитель (`;`) после вызова функции `printf`.

В языке C этот разделитель используется для отделения инструкций друг от друга. Его отсутствие приведет к ошибке компиляции.


=== Возврат в операционную систему

[source,c]
----
    return 0;
----

При объявлении функции `main` мы указали, что в конце работы функция вернет целочисленное значение, которое будет интерпретировано операционной системой как код возврата программы. Инструкция `return` делает именно это - завершает выполнение `main` и возвращает следующее за ней значение ОС.

В конце инструкции мы также видим обязательный разделитель `;`.

== Закрытие блока

[source,c]
----
}
----

Закрывающая фигурная скобка сообщает компилятору, что тело функции `main` закончилось. На этом программа завершает свою работу.

== Как это превращается в программу?

В отличие от таких языков, как Python или JavaScript, код на C нельзя просто запустить «как есть». Текст, который мы написали выше — это *исходный код* (обычно он сохраняется в файле с расширением `.c`, например, `hello.c`). Это текст для людей.

Чтобы компьютер понял наш код, его нужно перевести на машинный язык (в набор нулей и единиц). Этим занимается специальная программа — *компилятор*. 

Процесс выглядит так:

. Вы пишете код в файле `hello.c`.
. Скармливаете его компилятору (например, с помощью команды `gcc hello.c -o hello` в терминале).
. Компилятор проверяет код на ошибки, переводит его и создает *исполняемый файл* (в Windows это будет `hello.exe`, в Linux/macOS — просто `hello`).
. Вы запускаете этот файл, и на экране появляется заветное:
+
[source,text]
----
Hello, World!
----

== Подведем итог

Ваша первая программа состоит из:

. Подключения нужных инструментов (`#include`).
. Точки входа в программу (`main`).
. Полезного действия (`printf`).
. Корректного завершения (`return 0`).

Пока вам не нужно запоминать каждую мелочь. Главное — усвоить структуру: *библиотеки -> главная функция -> действия внутри фигурных скобок -> точка с запятой в конце команд*. 

Поздравляю! Вы написали свою первую программу на C. В следующей главе мы узнаем, как хранить данные в памяти компьютера, и познакомимся с переменными.